import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Maître Cuisinier</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       <Image src="/logov1-2.png" width={256} height={256}/>
       <h2>L&apos;été est là!<br/>L&apos;argent, c&apos;est maintenant !</h2>
      </main>
    </div>
  )
}
